# Default values for metered-usage-insight.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: hub.opsramp.com/analytics-apps/metered-usage-insight
  pullPolicy: Always
  tag: latest

ingress:
  enabled: true
  className: ""
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
  hosts:
    - paths:
        - path: /analytics-apps(/|$)(.*)
          pathType: Prefix
  tls: []

deployment:
  containerPort: 8050
  resources:
    limits:
      cpu: 500m
    requests:
      cpu: 200m

service:
  type: ClusterIP
  port: 9000
  targetPort: 8050
  externalIPs:
    - 176.13.17.232
    - 176.13.28.199
    - 176.13.24.63

env:
  - name: "PLATFORM_ROUTE"
    value: "analytics-apps"
  - name: "DATA_API_BASE_URL"
    value: "https://asura.opsramp.net"
  - name: "APP_SERVICE_BASE_URL"
    value: "http://13.57.187.238:8001/oap-api/v1"
  - name: "OAP_APP_ID"
    value: "32a1bc14-c471-46a4-9b0a-9823h293"
  - name: "INCLUDE_WRAPPER"
    value: "true"
  - name: "ON_PROXY"
    value: "false"
